from .health import router as health_router
from .uploads import router as uploads_router
from .mappings import router as mappings_router
from .processing import router as processing_router
from .analysis import router as analysis_router
from .users import router as users_router
from .admin import router as admin_router
from .organizations import router as organizations_router
from .processes import router as processes_router
