"""schema_driven_dev_migration

Revision ID: 73e54e8b10ef
Revises: 018_deprecate_dag_tables
Create Date: 2026-01-06 21:40:12.641444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73e54e8b10ef'
down_revision: Union[str, None] = '018_deprecate_dag_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('enabled_for_orgs_json', sa.Text(), nullable=True),
    sa.Column('enabled_for_users_json', sa.Text(), nullable=True),
    sa.Column('percentage_rollout', sa.Integer(), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flags_enabled'), 'feature_flags', ['enabled'], unique=False)
    op.create_index(op.f('ix_feature_flags_name'), 'feature_flags', ['name'], unique=True)
    op.create_table('api_usage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_usage_org_id'), 'api_usage', ['org_id'], unique=False)
    op.create_index('ix_api_usage_org_period', 'api_usage', ['org_id', 'period_start', 'period_end'], unique=False)
    op.create_index(op.f('ix_api_usage_resource_type'), 'api_usage', ['resource_type'], unique=False)
    op.create_index(op.f('ix_api_usage_user_id'), 'api_usage', ['user_id'], unique=False)
    op.create_table('workflow_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('task_name', sa.String(length=100), nullable=False),
    sa.Column('task_order', sa.Integer(), nullable=False),
    sa.Column('temporal_activity_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('input_params_json', sa.Text(), nullable=True),
    sa.Column('output_result_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details_json', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflow_tasks_order', 'workflow_tasks', ['workflow_id', 'task_order'], unique=False)
    op.create_index(op.f('ix_workflow_tasks_status'), 'workflow_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_tasks_workflow_id'), 'workflow_tasks', ['workflow_id'], unique=False)
    op.create_table('process_variants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('activity_sequence_json', sa.Text(), nullable=False),
    sa.Column('activity_sequence_hash', sa.String(length=64), nullable=False),
    sa.Column('case_count', sa.Integer(), nullable=False),
    sa.Column('frequency_percent', sa.Float(), nullable=True),
    sa.Column('avg_duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_variants_dataset_id'), 'process_variants', ['dataset_id'], unique=False)
    op.create_index('ix_variants_case_count', 'process_variants', ['dataset_id', 'case_count'], unique=False)
    op.create_index('ix_variants_dataset_hash', 'process_variants', ['dataset_id', 'activity_sequence_hash'], unique=True)
    op.drop_index(op.f('ix_dag_run_steps_celery_task_id'), table_name='dag_run_steps')
    op.drop_index(op.f('ix_dag_run_steps_dag_run_id'), table_name='dag_run_steps')
    op.drop_index(op.f('ix_dag_run_steps_status'), table_name='dag_run_steps')
    op.drop_table('dag_run_steps')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_dag_definition_edges_dag_id'), table_name='dag_definition_edges')
    op.drop_table('dag_definition_edges')
    op.drop_index(op.f('ix_dag_runs_dag_definition_id'), table_name='dag_runs')
    op.drop_index(op.f('ix_dag_runs_status'), table_name='dag_runs')
    op.drop_index(op.f('ix_dag_runs_user_id'), table_name='dag_runs')
    op.drop_table('dag_runs')
    op.drop_index(op.f('ix_dag_definition_steps_dag_id'), table_name='dag_definition_steps')
    op.drop_table('dag_definition_steps')
    op.drop_index(op.f('ix_dag_definitions_is_active'), table_name='dag_definitions')
    op.drop_index(op.f('ix_dag_definitions_name'), table_name='dag_definitions')
    op.drop_table('dag_definitions')
    op.add_column('analyses', sa.Column('created_by', sa.String(length=36), nullable=True))
    op.add_column('analyses', sa.Column('result_full_path', sa.String(length=500), nullable=True))
    op.alter_column('analyses', 'workflow_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.create_index(op.f('ix_analyses_analysis_type'), 'analyses', ['analysis_type'], unique=False)
    op.create_index(op.f('ix_analyses_created_by'), 'analyses', ['created_by'], unique=False)
    op.create_index(op.f('ix_analyses_dataset_id'), 'analyses', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_analyses_model_id'), 'analyses', ['model_id'], unique=False)
    op.create_index(op.f('ix_analyses_status'), 'analyses', ['status'], unique=False)
    op.create_foreign_key(None, 'analyses', 'workflows', ['workflow_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'analyses', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('analytics_cache', sa.Column('parameters_hash', sa.String(length=64), nullable=True))
    op.add_column('analytics_cache', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_analytics_cache_dataset_id'), 'analytics_cache', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_analytics_cache_expires_at'), 'analytics_cache', ['expires_at'], unique=False)
    op.create_index('ix_analytics_cache_unique', 'analytics_cache', ['dataset_id', 'metric_type', 'parameters_hash'], unique=True)
    op.drop_index(op.f('ix_async_jobs_dag_run_id'), table_name='async_jobs')
    op.drop_index(op.f('ix_async_jobs_dag_step_id'), table_name='async_jobs')
    op.drop_column('async_jobs', 'dag_step_id')
    op.drop_column('async_jobs', 'dag_run_id')
    op.add_column('conformance_results', sa.Column('analysis_id', sa.String(length=36), nullable=True))
    op.add_column('conformance_results', sa.Column('total_traces', sa.Integer(), nullable=True))
    op.add_column('conformance_results', sa.Column('fitting_traces', sa.Integer(), nullable=True))
    op.add_column('conformance_results', sa.Column('deviations_json', sa.Text(), nullable=True))
    op.add_column('conformance_results', sa.Column('deviation_patterns_json', sa.Text(), nullable=True))
    op.create_index('ix_conformance_dataset_model', 'conformance_results', ['dataset_id', 'model_id'], unique=False)
    op.create_index(op.f('ix_conformance_results_analysis_id'), 'conformance_results', ['analysis_id'], unique=True)
    op.create_index(op.f('ix_conformance_results_dataset_id'), 'conformance_results', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_conformance_results_model_id'), 'conformance_results', ['model_id'], unique=False)
    op.create_foreign_key(None, 'conformance_results', 'analyses', ['analysis_id'], ['id'], ondelete='CASCADE')
    op.add_column('graph_cache', sa.Column('filter_params_hash', sa.String(length=64), nullable=True))
    op.add_column('graph_cache', sa.Column('layout_json', sa.Text(), nullable=True))
    op.add_column('graph_cache', sa.Column('svg_content', sa.Text(), nullable=True))
    op.add_column('graph_cache', sa.Column('access_count', sa.Integer(), nullable=False))
    op.add_column('graph_cache', sa.Column('last_accessed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_graph_cache_expires_at'), 'graph_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_graph_cache_model_id'), 'graph_cache', ['model_id'], unique=False)
    op.create_index('ix_graph_cache_unique', 'graph_cache', ['model_id', 'abstraction_level', 'layout_algorithm', 'filter_params_hash'], unique=True)
    op.add_column('oc_petri_nets', sa.Column('dataset_id', sa.String(length=36), nullable=False))
    op.create_index(op.f('ix_oc_petri_nets_dataset_id'), 'oc_petri_nets', ['dataset_id'], unique=False)
    op.drop_constraint(None, 'oc_petri_nets', type_='foreignkey')
    op.create_foreign_key(None, 'oc_petri_nets', 'ocel_logs', ['dataset_id'], ['id'], ondelete='CASCADE')
    op.drop_column('oc_petri_nets', 'log_id')
    op.add_column('ocel2_events', sa.Column('source_dataset_id', sa.String(length=36), nullable=True))
    op.drop_constraint(None, 'ocel2_events', type_='foreignkey')
    op.create_foreign_key(None, 'ocel2_events', 'datasets', ['source_dataset_id'], ['id'], ondelete='SET NULL')
    op.drop_column('ocel2_events', 'source_log_id')
    op.add_column('ocel_object_types', sa.Column('dataset_id', sa.String(length=36), nullable=False))
    op.create_index(op.f('ix_ocel_object_types_dataset_id'), 'ocel_object_types', ['dataset_id'], unique=False)
    op.drop_constraint(None, 'ocel_object_types', type_='foreignkey')
    op.create_foreign_key(None, 'ocel_object_types', 'ocel_logs', ['dataset_id'], ['id'], ondelete='CASCADE')
    op.drop_column('ocel_object_types', 'log_id')
    op.add_column('prediction_models', sa.Column('created_by', sa.String(length=36), nullable=True))
    op.add_column('prediction_models', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('prediction_models', sa.Column('storage_path', sa.String(length=500), nullable=True))
    op.add_column('prediction_models', sa.Column('training_config_json', sa.Text(), nullable=True))
    op.add_column('prediction_models', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('prediction_models', sa.Column('workflow_id', sa.String(length=36), nullable=True))
    op.add_column('prediction_models', sa.Column('training_duration_seconds', sa.Integer(), nullable=True))
    op.add_column('prediction_models', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('prediction_models', 'model_binary',
               existing_type=sa.BLOB(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('prediction_models', 'trained_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_index(op.f('ix_prediction_models_algorithm'), 'prediction_models', ['algorithm'], unique=False)
    op.create_index(op.f('ix_prediction_models_created_by'), 'prediction_models', ['created_by'], unique=False)
    op.create_index(op.f('ix_prediction_models_dataset_id'), 'prediction_models', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_prediction_models_status'), 'prediction_models', ['status'], unique=False)
    op.create_index(op.f('ix_prediction_models_target_type'), 'prediction_models', ['target_type'], unique=False)
    op.create_index(op.f('ix_prediction_models_workflow_id'), 'prediction_models', ['workflow_id'], unique=False)
    op.create_foreign_key(None, 'prediction_models', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'prediction_models', 'workflows', ['workflow_id'], ['id'], ondelete='SET NULL')
    op.add_column('predictions', sa.Column('case_id', sa.String(length=255), nullable=False))
    op.add_column('predictions', sa.Column('actual_outcome_json', sa.Text(), nullable=True))
    op.add_column('predictions', sa.Column('was_correct', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_predictions_case_id'), 'predictions', ['case_id'], unique=False)
    op.create_index('ix_predictions_model_case', 'predictions', ['model_id', 'case_id'], unique=False)
    op.create_index(op.f('ix_predictions_model_id'), 'predictions', ['model_id'], unique=False)
    op.create_index(op.f('ix_predictions_predicted_at'), 'predictions', ['predicted_at'], unique=False)
    op.add_column('process_cases', sa.Column('variant_id', sa.String(length=36), nullable=True))
    op.add_column('process_cases', sa.Column('event_count', sa.Integer(), nullable=False))
    op.add_column('process_cases', sa.Column('duration_seconds', sa.BigInteger(), nullable=True))
    op.add_column('process_cases', sa.Column('attributes_json', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_process_cases_case_id'), table_name='process_cases')
    op.create_index('ix_cases_dataset_case_id', 'process_cases', ['dataset_id', 'case_id'], unique=True)
    op.create_index(op.f('ix_process_cases_dataset_id'), 'process_cases', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_process_cases_duration_seconds'), 'process_cases', ['duration_seconds'], unique=False)
    op.create_index(op.f('ix_process_cases_start_time'), 'process_cases', ['start_time'], unique=False)
    op.create_index(op.f('ix_process_cases_variant_id'), 'process_cases', ['variant_id'], unique=False)
    op.create_foreign_key(None, 'process_cases', 'process_variants', ['variant_id'], ['id'], ondelete='SET NULL')
    op.add_column('process_events', sa.Column('dataset_id', sa.String(length=36), nullable=False))
    op.add_column('process_events', sa.Column('end_timestamp', sa.DateTime(), nullable=True))
    op.add_column('process_events', sa.Column('event_index', sa.Integer(), nullable=False))
    op.create_index('ix_events_case_index', 'process_events', ['case_ref_id', 'event_index'], unique=False)
    op.create_index('ix_events_dataset_activity', 'process_events', ['dataset_id', 'activity_id'], unique=False)
    op.create_index('ix_events_dataset_timestamp', 'process_events', ['dataset_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_process_events_activity_id'), 'process_events', ['activity_id'], unique=False)
    op.create_index(op.f('ix_process_events_case_ref_id'), 'process_events', ['case_ref_id'], unique=False)
    op.create_index(op.f('ix_process_events_dataset_id'), 'process_events', ['dataset_id'], unique=False)
    op.create_foreign_key(None, 'process_events', 'lookup_resources', ['resource_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'process_events', 'lookup_activities', ['activity_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'process_events', 'datasets', ['dataset_id'], ['id'], ondelete='CASCADE')
    op.add_column('process_model_metrics', sa.Column('dataset_id', sa.String(length=36), nullable=True))
    op.add_column('process_model_metrics', sa.Column('fitness', sa.Float(), nullable=True))
    op.add_column('process_model_metrics', sa.Column('precision', sa.Float(), nullable=True))
    op.add_column('process_model_metrics', sa.Column('generalization', sa.Float(), nullable=True))
    op.add_column('process_model_metrics', sa.Column('simplicity', sa.Float(), nullable=True))
    op.add_column('process_model_metrics', sa.Column('f_score', sa.Float(), nullable=True))
    op.add_column('process_model_metrics', sa.Column('fitting_traces_count', sa.Integer(), nullable=True))
    op.add_column('process_model_metrics', sa.Column('non_fitting_traces_count', sa.Integer(), nullable=True))
    op.add_column('process_model_metrics', sa.Column('fitting_traces_percent', sa.Float(), nullable=True))
    op.add_column('process_model_metrics', sa.Column('average_trace_fitness', sa.Float(), nullable=True))
    op.add_column('process_model_metrics', sa.Column('average_alignment_cost', sa.Float(), nullable=True))
    op.add_column('process_model_metrics', sa.Column('alignment_details_json', sa.Text(), nullable=True))
    op.add_column('process_model_metrics', sa.Column('total_places', sa.Integer(), nullable=True))
    op.add_column('process_model_metrics', sa.Column('total_arcs', sa.Integer(), nullable=True))
    op.add_column('process_model_metrics', sa.Column('silent_transitions', sa.Integer(), nullable=True))
    op.add_column('process_model_metrics', sa.Column('evaluation_method', sa.String(length=50), nullable=True))
    op.add_column('process_model_metrics', sa.Column('computation_time_ms', sa.Integer(), nullable=True))
    op.create_index('ix_model_metrics_model_dataset', 'process_model_metrics', ['model_id', 'dataset_id'], unique=False)
    op.create_index(op.f('ix_process_model_metrics_dataset_id'), 'process_model_metrics', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_process_model_metrics_model_id'), 'process_model_metrics', ['model_id'], unique=False)
    op.create_foreign_key(None, 'process_model_metrics', 'datasets', ['dataset_id'], ['id'], ondelete='SET NULL')
    op.add_column('process_models', sa.Column('created_by', sa.String(length=36), nullable=True))
    op.add_column('process_models', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('process_models', sa.Column('model_type', sa.String(length=50), nullable=False))
    op.add_column('process_models', sa.Column('storage_path', sa.String(length=500), nullable=True))
    op.add_column('process_models', sa.Column('graph_json', sa.Text(), nullable=True))
    op.add_column('process_models', sa.Column('discovery_algorithm', sa.String(length=50), nullable=True))
    op.add_column('process_models', sa.Column('discovery_params_json', sa.Text(), nullable=True))
    op.add_column('process_models', sa.Column('discovery_workflow_id', sa.String(length=36), nullable=True))
    op.add_column('process_models', sa.Column('is_discovered', sa.Boolean(), nullable=False))
    op.add_column('process_models', sa.Column('is_reference', sa.Boolean(), nullable=False))
    op.add_column('process_models', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('process_models', sa.Column('parent_model_id', sa.String(length=36), nullable=True))
    op.alter_column('process_models', 'miner_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index(op.f('ix_process_models_created_by'), 'process_models', ['created_by'], unique=False)
    op.create_index(op.f('ix_process_models_dataset_id'), 'process_models', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_process_models_discovery_algorithm'), 'process_models', ['discovery_algorithm'], unique=False)
    op.create_index(op.f('ix_process_models_discovery_workflow_id'), 'process_models', ['discovery_workflow_id'], unique=False)
    op.create_index(op.f('ix_process_models_is_reference'), 'process_models', ['is_reference'], unique=False)
    op.create_index(op.f('ix_process_models_model_type'), 'process_models', ['model_type'], unique=False)
    op.create_index(op.f('ix_process_models_parent_model_id'), 'process_models', ['parent_model_id'], unique=False)
    op.create_foreign_key(None, 'process_models', 'workflows', ['discovery_workflow_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'process_models', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'process_models', 'process_models', ['parent_model_id'], ['id'], ondelete='SET NULL')
    op.add_column('recommendations', sa.Column('action_description', sa.Text(), nullable=True))
    op.add_column('recommendations', sa.Column('expected_impact_json', sa.Text(), nullable=True))
    op.add_column('recommendations', sa.Column('handled_by', sa.String(length=36), nullable=True))
    op.add_column('recommendations', sa.Column('handled_at', sa.DateTime(), nullable=True))
    op.add_column('recommendations', sa.Column('feedback', sa.Text(), nullable=True))
    op.add_column('recommendations', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_recommendations_case_id'), 'recommendations', ['case_id'], unique=False)
    op.create_index(op.f('ix_recommendations_created_at'), 'recommendations', ['created_at'], unique=False)
    op.create_index('ix_recommendations_dataset_case', 'recommendations', ['dataset_id', 'case_id'], unique=False)
    op.create_index(op.f('ix_recommendations_dataset_id'), 'recommendations', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_recommendations_handled_by'), 'recommendations', ['handled_by'], unique=False)
    op.create_index(op.f('ix_recommendations_signal_type'), 'recommendations', ['signal_type'], unique=False)
    op.create_index(op.f('ix_recommendations_state'), 'recommendations', ['state'], unique=False)
    op.create_foreign_key(None, 'recommendations', 'users', ['handled_by'], ['id'], ondelete='SET NULL')
    op.add_column('workflows', sa.Column('temporal_workflow_id', sa.String(length=255), nullable=True))
    op.add_column('workflows', sa.Column('temporal_run_id', sa.String(length=255), nullable=True))
    op.add_column('workflows', sa.Column('org_id', sa.String(length=36), nullable=False))
    op.add_column('workflows', sa.Column('user_id', sa.String(length=36), nullable=False))
    op.add_column('workflows', sa.Column('workflow_type', sa.String(length=50), nullable=False))
    op.add_column('workflows', sa.Column('entity_type', sa.String(length=50), nullable=True))
    op.add_column('workflows', sa.Column('entity_id', sa.String(length=36), nullable=True))
    op.add_column('workflows', sa.Column('input_params_json', sa.Text(), nullable=False))
    op.add_column('workflows', sa.Column('output_result_json', sa.Text(), nullable=True))
    op.add_column('workflows', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('workflows', sa.Column('progress_percent', sa.Integer(), nullable=False))
    op.add_column('workflows', sa.Column('current_step', sa.String(length=100), nullable=True))
    op.add_column('workflows', sa.Column('error_code', sa.String(length=50), nullable=True))
    op.add_column('workflows', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('workflows', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('workflows', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('workflows', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('workflows', sa.Column('timeout_seconds', sa.Integer(), nullable=True))
    op.create_index('ix_workflows_entity', 'workflows', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_workflows_org_id'), 'workflows', ['org_id'], unique=False)
    op.create_index(op.f('ix_workflows_status'), 'workflows', ['status'], unique=False)
    op.create_index('ix_workflows_status_type', 'workflows', ['status', 'workflow_type'], unique=False)
    op.create_index(op.f('ix_workflows_temporal_workflow_id'), 'workflows', ['temporal_workflow_id'], unique=False)
    op.create_index(op.f('ix_workflows_user_id'), 'workflows', ['user_id'], unique=False)
    op.create_index(op.f('ix_workflows_workflow_type'), 'workflows', ['workflow_type'], unique=False)
    op.create_foreign_key(None, 'workflows', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'workflows', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('workflows', 'steps_json')
    op.drop_column('workflows', 'name')
    op.drop_column('workflows', 'updated_at')
    op.drop_column('workflows', 'schedule')
    op.drop_column('workflows', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('is_active', sa.BOOLEAN(), nullable=False))
    op.add_column('workflows', sa.Column('schedule', sa.VARCHAR(length=100), nullable=True))
    op.add_column('workflows', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('workflows', sa.Column('name', sa.VARCHAR(length=255), nullable=False))
    op.add_column('workflows', sa.Column('steps_json', sa.TEXT(), nullable=False))
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.drop_index(op.f('ix_workflows_workflow_type'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_user_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_temporal_workflow_id'), table_name='workflows')
    op.drop_index('ix_workflows_status_type', table_name='workflows')
    op.drop_index(op.f('ix_workflows_status'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_org_id'), table_name='workflows')
    op.drop_index('ix_workflows_entity', table_name='workflows')
    op.drop_column('workflows', 'timeout_seconds')
    op.drop_column('workflows', 'completed_at')
    op.drop_column('workflows', 'started_at')
    op.drop_column('workflows', 'retry_count')
    op.drop_column('workflows', 'error_message')
    op.drop_column('workflows', 'error_code')
    op.drop_column('workflows', 'current_step')
    op.drop_column('workflows', 'progress_percent')
    op.drop_column('workflows', 'status')
    op.drop_column('workflows', 'output_result_json')
    op.drop_column('workflows', 'input_params_json')
    op.drop_column('workflows', 'entity_id')
    op.drop_column('workflows', 'entity_type')
    op.drop_column('workflows', 'workflow_type')
    op.drop_column('workflows', 'user_id')
    op.drop_column('workflows', 'org_id')
    op.drop_column('workflows', 'temporal_run_id')
    op.drop_column('workflows', 'temporal_workflow_id')
    op.drop_constraint(None, 'recommendations', type_='foreignkey')
    op.drop_index(op.f('ix_recommendations_state'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_signal_type'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_handled_by'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_dataset_id'), table_name='recommendations')
    op.drop_index('ix_recommendations_dataset_case', table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_created_at'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_case_id'), table_name='recommendations')
    op.drop_column('recommendations', 'expires_at')
    op.drop_column('recommendations', 'feedback')
    op.drop_column('recommendations', 'handled_at')
    op.drop_column('recommendations', 'handled_by')
    op.drop_column('recommendations', 'expected_impact_json')
    op.drop_column('recommendations', 'action_description')
    op.drop_constraint(None, 'process_models', type_='foreignkey')
    op.drop_constraint(None, 'process_models', type_='foreignkey')
    op.drop_constraint(None, 'process_models', type_='foreignkey')
    op.drop_index(op.f('ix_process_models_parent_model_id'), table_name='process_models')
    op.drop_index(op.f('ix_process_models_model_type'), table_name='process_models')
    op.drop_index(op.f('ix_process_models_is_reference'), table_name='process_models')
    op.drop_index(op.f('ix_process_models_discovery_workflow_id'), table_name='process_models')
    op.drop_index(op.f('ix_process_models_discovery_algorithm'), table_name='process_models')
    op.drop_index(op.f('ix_process_models_dataset_id'), table_name='process_models')
    op.drop_index(op.f('ix_process_models_created_by'), table_name='process_models')
    op.alter_column('process_models', 'miner_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('process_models', 'parent_model_id')
    op.drop_column('process_models', 'version')
    op.drop_column('process_models', 'is_reference')
    op.drop_column('process_models', 'is_discovered')
    op.drop_column('process_models', 'discovery_workflow_id')
    op.drop_column('process_models', 'discovery_params_json')
    op.drop_column('process_models', 'discovery_algorithm')
    op.drop_column('process_models', 'graph_json')
    op.drop_column('process_models', 'storage_path')
    op.drop_column('process_models', 'model_type')
    op.drop_column('process_models', 'description')
    op.drop_column('process_models', 'created_by')
    op.drop_constraint(None, 'process_model_metrics', type_='foreignkey')
    op.drop_index(op.f('ix_process_model_metrics_model_id'), table_name='process_model_metrics')
    op.drop_index(op.f('ix_process_model_metrics_dataset_id'), table_name='process_model_metrics')
    op.drop_index('ix_model_metrics_model_dataset', table_name='process_model_metrics')
    op.drop_column('process_model_metrics', 'computation_time_ms')
    op.drop_column('process_model_metrics', 'evaluation_method')
    op.drop_column('process_model_metrics', 'silent_transitions')
    op.drop_column('process_model_metrics', 'total_arcs')
    op.drop_column('process_model_metrics', 'total_places')
    op.drop_column('process_model_metrics', 'alignment_details_json')
    op.drop_column('process_model_metrics', 'average_alignment_cost')
    op.drop_column('process_model_metrics', 'average_trace_fitness')
    op.drop_column('process_model_metrics', 'fitting_traces_percent')
    op.drop_column('process_model_metrics', 'non_fitting_traces_count')
    op.drop_column('process_model_metrics', 'fitting_traces_count')
    op.drop_column('process_model_metrics', 'f_score')
    op.drop_column('process_model_metrics', 'simplicity')
    op.drop_column('process_model_metrics', 'generalization')
    op.drop_column('process_model_metrics', 'precision')
    op.drop_column('process_model_metrics', 'fitness')
    op.drop_column('process_model_metrics', 'dataset_id')
    op.drop_constraint(None, 'process_events', type_='foreignkey')
    op.drop_constraint(None, 'process_events', type_='foreignkey')
    op.drop_constraint(None, 'process_events', type_='foreignkey')
    op.drop_index(op.f('ix_process_events_dataset_id'), table_name='process_events')
    op.drop_index(op.f('ix_process_events_case_ref_id'), table_name='process_events')
    op.drop_index(op.f('ix_process_events_activity_id'), table_name='process_events')
    op.drop_index('ix_events_dataset_timestamp', table_name='process_events')
    op.drop_index('ix_events_dataset_activity', table_name='process_events')
    op.drop_index('ix_events_case_index', table_name='process_events')
    op.drop_column('process_events', 'event_index')
    op.drop_column('process_events', 'end_timestamp')
    op.drop_column('process_events', 'dataset_id')
    op.drop_constraint(None, 'process_cases', type_='foreignkey')
    op.drop_index(op.f('ix_process_cases_variant_id'), table_name='process_cases')
    op.drop_index(op.f('ix_process_cases_start_time'), table_name='process_cases')
    op.drop_index(op.f('ix_process_cases_duration_seconds'), table_name='process_cases')
    op.drop_index(op.f('ix_process_cases_dataset_id'), table_name='process_cases')
    op.drop_index('ix_cases_dataset_case_id', table_name='process_cases')
    op.create_index(op.f('ix_process_cases_case_id'), 'process_cases', ['case_id'], unique=False)
    op.drop_column('process_cases', 'attributes_json')
    op.drop_column('process_cases', 'duration_seconds')
    op.drop_column('process_cases', 'event_count')
    op.drop_column('process_cases', 'variant_id')
    op.drop_index(op.f('ix_predictions_predicted_at'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_model_id'), table_name='predictions')
    op.drop_index('ix_predictions_model_case', table_name='predictions')
    op.drop_index(op.f('ix_predictions_case_id'), table_name='predictions')
    op.drop_column('predictions', 'was_correct')
    op.drop_column('predictions', 'actual_outcome_json')
    op.drop_column('predictions', 'case_id')
    op.drop_constraint(None, 'prediction_models', type_='foreignkey')
    op.drop_constraint(None, 'prediction_models', type_='foreignkey')
    op.drop_index(op.f('ix_prediction_models_workflow_id'), table_name='prediction_models')
    op.drop_index(op.f('ix_prediction_models_target_type'), table_name='prediction_models')
    op.drop_index(op.f('ix_prediction_models_status'), table_name='prediction_models')
    op.drop_index(op.f('ix_prediction_models_dataset_id'), table_name='prediction_models')
    op.drop_index(op.f('ix_prediction_models_created_by'), table_name='prediction_models')
    op.drop_index(op.f('ix_prediction_models_algorithm'), table_name='prediction_models')
    op.alter_column('prediction_models', 'trained_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('prediction_models', 'model_binary',
               existing_type=sa.Text(),
               type_=sa.BLOB(),
               existing_nullable=True)
    op.drop_column('prediction_models', 'created_at')
    op.drop_column('prediction_models', 'training_duration_seconds')
    op.drop_column('prediction_models', 'workflow_id')
    op.drop_column('prediction_models', 'status')
    op.drop_column('prediction_models', 'training_config_json')
    op.drop_column('prediction_models', 'storage_path')
    op.drop_column('prediction_models', 'name')
    op.drop_column('prediction_models', 'created_by')
    op.add_column('ocel_object_types', sa.Column('log_id', sa.VARCHAR(length=36), nullable=False))
    op.drop_constraint(None, 'ocel_object_types', type_='foreignkey')
    op.create_foreign_key(None, 'ocel_object_types', 'ocel_logs', ['log_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_ocel_object_types_dataset_id'), table_name='ocel_object_types')
    op.drop_column('ocel_object_types', 'dataset_id')
    op.add_column('ocel2_events', sa.Column('source_log_id', sa.VARCHAR(length=36), nullable=True))
    op.drop_constraint(None, 'ocel2_events', type_='foreignkey')
    op.create_foreign_key(None, 'ocel2_events', 'datasets', ['source_log_id'], ['id'], ondelete='SET NULL')
    op.drop_column('ocel2_events', 'source_dataset_id')
    op.add_column('oc_petri_nets', sa.Column('log_id', sa.VARCHAR(length=36), nullable=False))
    op.drop_constraint(None, 'oc_petri_nets', type_='foreignkey')
    op.create_foreign_key(None, 'oc_petri_nets', 'ocel_logs', ['log_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_oc_petri_nets_dataset_id'), table_name='oc_petri_nets')
    op.drop_column('oc_petri_nets', 'dataset_id')
    op.drop_index('ix_graph_cache_unique', table_name='graph_cache')
    op.drop_index(op.f('ix_graph_cache_model_id'), table_name='graph_cache')
    op.drop_index(op.f('ix_graph_cache_expires_at'), table_name='graph_cache')
    op.drop_column('graph_cache', 'last_accessed_at')
    op.drop_column('graph_cache', 'access_count')
    op.drop_column('graph_cache', 'svg_content')
    op.drop_column('graph_cache', 'layout_json')
    op.drop_column('graph_cache', 'filter_params_hash')
    op.drop_constraint(None, 'conformance_results', type_='foreignkey')
    op.drop_index(op.f('ix_conformance_results_model_id'), table_name='conformance_results')
    op.drop_index(op.f('ix_conformance_results_dataset_id'), table_name='conformance_results')
    op.drop_index(op.f('ix_conformance_results_analysis_id'), table_name='conformance_results')
    op.drop_index('ix_conformance_dataset_model', table_name='conformance_results')
    op.drop_column('conformance_results', 'deviation_patterns_json')
    op.drop_column('conformance_results', 'deviations_json')
    op.drop_column('conformance_results', 'fitting_traces')
    op.drop_column('conformance_results', 'total_traces')
    op.drop_column('conformance_results', 'analysis_id')
    op.add_column('async_jobs', sa.Column('dag_run_id', sa.VARCHAR(length=36), nullable=True))
    op.add_column('async_jobs', sa.Column('dag_step_id', sa.VARCHAR(length=36), nullable=True))
    op.create_index(op.f('ix_async_jobs_dag_step_id'), 'async_jobs', ['dag_step_id'], unique=False)
    op.create_index(op.f('ix_async_jobs_dag_run_id'), 'async_jobs', ['dag_run_id'], unique=False)
    op.drop_index('ix_analytics_cache_unique', table_name='analytics_cache')
    op.drop_index(op.f('ix_analytics_cache_expires_at'), table_name='analytics_cache')
    op.drop_index(op.f('ix_analytics_cache_dataset_id'), table_name='analytics_cache')
    op.drop_column('analytics_cache', 'expires_at')
    op.drop_column('analytics_cache', 'parameters_hash')
    op.drop_constraint(None, 'analyses', type_='foreignkey')
    op.drop_constraint(None, 'analyses', type_='foreignkey')
    op.drop_index(op.f('ix_analyses_status'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_model_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_dataset_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_created_by'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_analysis_type'), table_name='analyses')
    op.alter_column('analyses', 'workflow_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('analyses', 'result_full_path')
    op.drop_column('analyses', 'created_by')
    op.create_table('dag_definitions',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dag_definitions_name'), 'dag_definitions', ['name'], unique=False)
    op.create_index(op.f('ix_dag_definitions_is_active'), 'dag_definitions', ['is_active'], unique=False)
    op.create_table('dag_definition_steps',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('dag_definition_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('task_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('default_params_json', sa.TEXT(), nullable=True),
    sa.Column('retry_policy_json', sa.TEXT(), nullable=True),
    sa.Column('timeout_seconds', sa.INTEGER(), server_default=sa.text("'3600'"), nullable=True),
    sa.Column('position', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['dag_definition_id'], ['dag_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dag_definition_id', 'name', name='uq_dag_definition_steps_name')
    )
    op.create_index(op.f('ix_dag_definition_steps_dag_id'), 'dag_definition_steps', ['dag_definition_id'], unique=False)
    op.create_table('dag_runs',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('dag_definition_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('trigger_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('context_json', sa.TEXT(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['dag_definition_id'], ['dag_definitions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dag_runs_user_id'), 'dag_runs', ['user_id'], unique=False)
    op.create_index(op.f('ix_dag_runs_status'), 'dag_runs', ['status'], unique=False)
    op.create_index(op.f('ix_dag_runs_dag_definition_id'), 'dag_runs', ['dag_definition_id'], unique=False)
    op.create_table('dag_definition_edges',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('dag_definition_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('from_step_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('to_step_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('condition_json', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['dag_definition_id'], ['dag_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_step_id'], ['dag_definition_steps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_step_id'], ['dag_definition_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dag_definition_id', 'from_step_id', 'to_step_id', name=op.f('uq_dag_definition_edges_from_to'))
    )
    op.create_index(op.f('ix_dag_definition_edges_dag_id'), 'dag_definition_edges', ['dag_definition_id'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('workflow_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('dataset_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('result_json', sa.TEXT(), nullable=True),
    sa.Column('error', sa.TEXT(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dag_run_steps',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('dag_run_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('definition_step_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('step_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('task_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('parameters_json', sa.TEXT(), nullable=True),
    sa.Column('result_json', sa.TEXT(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('retry_count', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('celery_task_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['dag_run_id'], ['dag_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['definition_step_id'], ['dag_definition_steps.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dag_run_steps_status'), 'dag_run_steps', ['status'], unique=False)
    op.create_index(op.f('ix_dag_run_steps_dag_run_id'), 'dag_run_steps', ['dag_run_id'], unique=False)
    op.create_index(op.f('ix_dag_run_steps_celery_task_id'), 'dag_run_steps', ['celery_task_id'], unique=False)
    op.drop_index('ix_variants_dataset_hash', table_name='process_variants')
    op.drop_index('ix_variants_case_count', table_name='process_variants')
    op.drop_index(op.f('ix_process_variants_dataset_id'), table_name='process_variants')
    op.drop_table('process_variants')
    op.drop_index(op.f('ix_workflow_tasks_workflow_id'), table_name='workflow_tasks')
    op.drop_index(op.f('ix_workflow_tasks_status'), table_name='workflow_tasks')
    op.drop_index('ix_workflow_tasks_order', table_name='workflow_tasks')
    op.drop_table('workflow_tasks')
    op.drop_index(op.f('ix_api_usage_user_id'), table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_resource_type'), table_name='api_usage')
    op.drop_index('ix_api_usage_org_period', table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_org_id'), table_name='api_usage')
    op.drop_table('api_usage')
    op.drop_index(op.f('ix_feature_flags_name'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_enabled'), table_name='feature_flags')
    op.drop_table('feature_flags')
    # ### end Alembic commands ###
