"""add_organization_workspace_user_hierarchy

Revision ID: 8f48c262ebc2
Revises: 006_add_state_machine_fields
Create Date: 2026-01-01 16:41:57.057174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f48c262ebc2'
down_revision: Union[str, None] = '006_add_state_machine_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.String(length=50), nullable=False),
    sa.Column('auth_provider_id', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('conformance_results', sa.Column('generalization', sa.Float(), nullable=True))
    op.add_column('conformance_results', sa.Column('simplicity', sa.Float(), nullable=True))
    op.add_column('conformance_results', sa.Column('f_score', sa.Float(), nullable=True))
    op.add_column('conformance_results', sa.Column('non_fitting_traces', sa.Integer(), nullable=True))
    op.add_column('conformance_results', sa.Column('average_alignment_cost', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('workspace_id', sa.String(length=36), nullable=True))
    # SQLite doesn't support ALTER for FK, so we skip the FK constraint at DB level
    # The FK relationship is enforced by SQLAlchemy ORM
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'workspace_id')
    op.drop_column('conformance_results', 'average_alignment_cost')
    op.drop_column('conformance_results', 'non_fitting_traces')
    op.drop_column('conformance_results', 'f_score')
    op.drop_column('conformance_results', 'simplicity')
    op.drop_column('conformance_results', 'generalization')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
