/**
 * API Hooks Library
 * 
 * Auto-generated React Query hooks from OpenAPI specification.
 * 
 * Usage:
 *   import { useGetDagsDefinitions, useTriggerRun } from '@frontend-new/api-hooks';
 * 
 * Generation:
 *   npm run generate:api
 * 
 * The hooks are generated by Orval and provide:
 * - Type-safe API calls
 * - React Query integration (caching, refetching, etc.)
 * - Automatic request cancellation
 */

// Re-export the custom axios instance for direct API calls if needed
export { axiosInstance, customInstance } from './axios-instance';

// Generated hooks will be exported from here after running `npm run generate:api`
// Example:
//   export * from './generated';
